#! /bin/sh

# Set Caps to Escape
setxkbmap -option caps:escape

# Start shortcuts
sxhkd &

# Set background
~/.fehbg

# Start compositor
picom --config ~/.config/picom/picom.conf &

# Bar
polybar default &

# Networking
nm-applet &

# Screenshot program
flameshot &

# Password Manager
keepassxc &

# We need this for any AWT app to actually function
wmname LG3D

bspc config border_width            2
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config focus_follows_pointer   true

bspc monitor -d term web ide 4 5 6

bspc rule -a KeePassXC desktop=^6 follow=on
